### ISSUE TITLE
Installation error in R 3.6.0

### ISSUE THREAD

**Issue by Yolanda-HT** [jhsiao999/peco#35]
Hi I was trying to install Peco from Github and got this:

```ERROR: this R is version 3.6.0, package 'peco' requires R >= 4.0```

Could you help me with this problem? Thanks!

**Comment by jhsiao999** [comment]
Hi,

The current release version of peco is built for the upcoming Bioconductor
release 3.11, which works for R version 4.0.0. I suggest updating to R
4.0.0 if you are a frequent Bioconductor user.

Meanwhile, I will create a git branch of peco for R 3.6.0 for users who are
not ready to upgrade to R4.0.0. Stay tuned!

Joyce

**Comment by Yolanda-HT** [comment]
Hi Joyce,

Thanks for the reply!

I am also looking for some suggestions in managing R environment. Since the
final release of R 4.0.0 is April 24th, would you suggest to update R base
now or wait for the final release?

Thanks again!

Best,
Huitian

**Comment by jdblischak** [comment]
@Yolanda-HT I'd recommend you wait until R 4.0.0 is officially released later this month before you update your local R installation.

I've sent PR #36 to relax the minimum required versions. @jhsiao999 still needs to review it before merging. If you're in a hurry, you can install peco directly from my fork using the command below:

```
remotes::install_github("jdblischak/peco@dependencies")
```

**Comment by jdblischak** [comment]
@Yolanda-HT You can now install directly from the main GitHub repository:

```
remotes::install_github("jhsiao999/peco")
```

**Comment by Yolanda-HT** [comment]
Thank you!!

Best,
Huitian
